leftnav:
- identifier: 00c53438-c415-e0c6-a3ce-7fac96c21631
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 603a8d9d-493d-8270-af92-3b3f2ed75c84
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 21164505-7e37-a289-dc77-cc11cd2f3fb0
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 9d206842-775b-9736-52ec-e3f48328722a
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 290b5bf7-0609-f793-5b6e-4bce7658a566
  name: Recitations
  url: /pages/recitations
  weight: 50
- identifier: 6d7f3f8b-a8f4-e271-62e1-a3c078d4074d
  name: Labs
  url: /pages/labs
  weight: 60
- identifier: 6ce3c0ef-aa05-c666-e55d-905e597c8e4d
  name: Assignments
  url: /pages/assignments
  weight: 70
- identifier: 8860cbb8-d8d4-896c-7697-a4dfee7e506f
  name: Exams
  url: /pages/exams
  weight: 80
- identifier: 1b7b5244-5bb2-888f-234a-c30570f2d271
  name: Tools
  url: /pages/tools
  weight: 90
